apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: game-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
