apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
