name: Deploy Analytics Service to EKS

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/analytics-service/**'              # Only trigger when analytics-service changes
      - '.github/workflows/deploy-analytics.yml'     # Or this workflow changes
      - 'analytics-deployment.yaml'                  # Or the deployment YAML changes

env:
  AWS_REGION: us-east-1
  ECR_REPO: 851725513473.dkr.ecr.us-east-1.amazonaws.com/analytics-service
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPO:$IMAGE_TAG ./Backend/analytics-service

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REPO:$IMAGE_TAG

      - name: Update image tag in analytics-deployment.yaml
        run: |
          sed -i "s|image: .*$|image: $ECR_REPO:$IMAGE_TAG|" analytics-deployment.yaml

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name lugx-gaming

      - name: Deploy to EKS
        run: |
          kubectl apply -f analytics-deployment.yaml
          kubectl apply -f analytics-service.yaml
