name: Deploy Order Service to EKS

on:
  push:
    branches: [main]
    paths:
      - 'Backend/order-service/**'
      - 'order-service-deployment.yaml'
      - 'order-service.yaml'
      - '.github/workflows/deploy-order.yml'

env:
  AWS_REGION: us-east-1
  ECR_REPO: 851725513473.dkr.ecr.us-east-1.amazonaws.com/order-service
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t $ECR_REPO:$IMAGE_TAG ./Backend/order-service
          docker push $ECR_REPO:$IMAGE_TAG

      - name: Update deployment YAML
        run: |
          sed -i "s|image: .*$|image: $ECR_REPO:$IMAGE_TAG|" order-service-deployment.yaml

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name lugex-gaming

      - name: Deploy to EKS
        run: |
          kubectl apply -f order-service-deployment.yaml
          kubectl apply -f order-service.yaml
